# Generated by Django 2.0.5 on 2018-05-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('vers', models.CharField(blank=True, max_length=5, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'app_ver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.TextField()),
                ('t_id', models.IntegerField()),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'del_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(blank=True, null=True, verbose_name='Дата разработки')),
                ('snils', models.CharField(max_length=15, verbose_name='СНИЛС')),
                ('lname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('fname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('sname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('bdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gndr', models.SmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж')], null=True, verbose_name='Пол')),
                ('docnum', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер документа')),
                ('docdt', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('prg', models.SmallIntegerField(blank=True, choices=[(1, 'ИПР'), (2, 'ПРП')], null=True, verbose_name='Программа: 1-ИПР, 2-ПРП')),
                ('prgnum', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер ИПР/ПРП')),
                ('prgdt', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ИПР')),
                ('mseid', models.CharField(max_length=36, verbose_name='Ключ ИПР/ПРП из ФБ МСЭ')),
                ('udt', models.DateTimeField(editable=False, verbose_name='')),
                ('adt', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Список ИПР и ПРП',
                'verbose_name_plural': 'Список ИПР и ПРП',
                'db_table': 'prg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrgOiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'prg_oiv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrgOkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'prg_okr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrgReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'prg_reg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrgRhb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('dt_exc', models.DateField(blank=True, null=True)),
                ('execut', models.CharField(blank=True, max_length=128, null=True)),
                ('par1', models.IntegerField(blank=True, null=True)),
                ('par2', models.IntegerField(blank=True, null=True)),
                ('par3', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'prg_rhb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbDic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_dic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbEvnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_evnt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbExc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('scode', models.CharField(blank=True, max_length=64, null=True)),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_exc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbGrp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_grp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbGtsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('scode', models.CharField(blank=True, max_length=20, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_gtsr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbTsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('scode', models.CharField(blank=True, max_length=20, null=True)),
                ('p374n', models.CharField(blank=True, max_length=20, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_tsr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('shname', models.CharField(blank=True, max_length=64, null=True)),
                ('arc', models.DateField(blank=True, null=True)),
                ('udt', models.DateTimeField()),
                ('adt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rhb_type',
                'managed': False,
            },
        ),
    ]
